name = "THM Forever Server Mods"
author = "ArcOnyx"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4e3033cfc8f2e501504865d25e23ded63779dc083163df1cca19c88528b301e"

[versions]
fabric = "0.19.1"
minecraft = "26.1.2"

[options]
datapack-folder = "resources/datapack"
